services:
    pcgf.privatecategories.permission_helper:
        class: pcgf\privatecategories\includes\permission_helper
        arguments:
            - '@auth'
            - '@dbal.conn'
            - '@config'
            - '%core.root_path%'
            - '%core.php_ext%'
    pcgf.privatecategories.listener:
        class: pcgf\privatecategories\event\listener
        arguments:
            - '@dbal.conn'
            - '@config'
            - '@template'
            - '@user'
            - '@auth'
            - '@controller.helper'
            - '@pcgf.privatecategories.permission_helper'
        tags:
            - { name: event.listener }
    pcgf.privatecategories.controller:
        class: pcgf\privatecategories\controller\controller
        arguments:
            - '@request'
            - '@dbal.conn'
            - '@auth'
            - '@user'
            - '@pcgf.privatecategories.permission_helper'