services:
    pcgf.privatecategories.listener:
        class: pcgf\privatecategories\event\listener
        arguments:
            - @dbal.conn
            - @config
            - @template
            - @user
            - @auth
        tags:
            - { name: event.listener }